name: Flutter CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                distribution: 'zulu'
                java-version: '21'
            - uses: subosito/flutter-action@v2
              with:
                channel: stable
                flutter-version: 3.22.0

            - run: flutter pub get

            - run: flutter analyze .

            - name: Build APK
              run: flutter build apk --split-per-abi --release

            - name: Build APP BUNDLE
              run: flutter build appbundle

            - name: Create Release
              uses: ncipollo/release-action@v1.14.0
              with:
                artifacts: "build/app/outputs/apk/release/*.apk, build/app/outputs/bundle/release/*.aab"
      
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v4
              with:
                name: release-apk
                path: build/app/outputs/apk/release/app-release.apk